env:
  es2021: true
  node: true
  jest: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
root: true
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: 'tsconfig.json'
  tsconfigRootDir : './'
plugins:
  - '@typescript-eslint/eslint-plugin'
rules: {
  '@typescript-eslint/interface-name-prefix': 'off',
  '@typescript-eslint/explicit-function-return-type': 'off',
  '@typescript-eslint/explicit-module-boundary-types': 'off',
  '@typescript-eslint/no-explicit-any': 'off',
}